
/*CRIANDO BANCO DE DADOS  UTILIZANDO MYSQL  WORKBENCH*/
CREATE DATABASE INNERSJOINS;


/* CRIANDO AS TABELAS */
CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM('M','F') NOT NULL,
	EMAIL VARCHAR(50) UNIQUE,
	CPF VARCHAR(15) UNIQUE
);
CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT, 
	RUA VARCHAR(30) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	ID_CLIENTE INT UNIQUE, 

	FOREIGN KEY(ID_CLIENTE)  /* CRIANDO AS CHAVES ESTRANGEIRAS */ 
	REFERENCES CLIENTE(IDCLIENTE) 
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT, 
	TIPO ENUM('RES','COM','CEL') NOT NULL,
	NUMERO INT NOT NULL,
	ID_CLIENTE INT, 

	FOREIGN KEY(ID_CLIENTE)  /* CRIANDO AS CHAVES ESTRANGEIRAS */ 
	REFERENCES CLIENTE(IDCLIENTE)
);


/* FAZENDO AS INSERÇÕES NAS TABELAS */ 
INSERT INTO CLIENTE (IDCLIENTE, NOME, SEXO, EMAIL, CPF)
VALUES
		(NULL,'JOAO','M','JOAOA@IG.COM','76567587887'),
		(NULL,'CARLOS','M','CARLOSA@IG.COM','5464553466'),
		(NULL,'ANA','F','ANA@IG.COM','456545678'),
		(NULL,'CLARA','F',NULL,'5687766856'),
		(NULL,'JORGE','M','JORGE@IG.COM','8756547688'),
		(NULL,'CELIA','M','JCELIA@IG.COM','5767876889');


INSERT INTO ENDERECO (IDENDERECO, RUA, BAIRRO, CIDADE, ESTADO, ID_CLIENTE )
VALUES	
		(NULL,'RUA ANTONIO SA','CENTRO','B. HORIZONTE','MG',4),
		(NULL,'RUA CAPITAO HERMES','CENTRO','RIO DE JANEIRO','RJ',1),
		(NULL,'RUA PRES VARGAS','JARDINS','SAO PAULO','SP',3),
		(NULL,'RUA ALFANDEGA','ESTACIO','RIO DE JANEIRO','RJ',2),
		(NULL,'RUA DO OUVIDOR','FLAMENGO','RIO DE JANEIRO','RJ',6),
		(NULL,'RUA URUGUAIANA','CENTRO','VITORIA','ES',5);

INSERT INTO TELEFONE (IDTELEFONE, TIPO, NUMERO, ID_CLIENTE)
VALUES
		(NULL,'CEL','78458743',5),
		(NULL,'RES','56576876',5),
		(NULL,'CEL','87866896',1),
		(NULL,'COM','54768899',2),
		(NULL,'RES','99667587',1),
		(NULL,'CEL','78989765',3),
		(NULL,'CEL','99766676',3),
		(NULL,'COM','66687899',1),
		(NULL,'RES','89986668',5),
		(NULL,'CEL','88687909',2);	


/*TESTANDO AS TABELAS*/
SELECT * FROM TELEFONE;
SELECT * FROM ENDERECO;
SELECT * FROM CLIENTE;


/* SELECAO, PROJECAO E JUNCAO */

/* PROJECAO -> É TUDO QUE VOCE QUER VER NA TELA */

SELECT NOW() AS DATA_ATUAL;

SELECT 2 + 2 AS SOMA;

SELECT 2 + 2 AS SOMA, NOME, NOW()
FROM CLIENTE;	

SELECT NOME, SEXO, EMAIL /* PROJECAO */
FROM CLIENTE /* ORIGEM */
WHERE SEXO = 'F'; /* SELECAO */

SELECT NUMERO /* PROJECAO */
FROM TELEFONE /* ORIGEM */
WHERE TIPO = 'CEL'; /* SELECAO */

---------------------------------------------------------------------------------------------------------------------------------------
/*PRIMEIRA BUSCA COMPOSTA - EM DUAS TABELAS*/
SELECT NOME, SEXO, BAIRRO, CIDADE /* PROJECAO */
FROM CLIENTE, ENDERECO /*ORIGEM */
WHERE IDCLIENTE = ID_CLIENTE; /* JUNCAO */

SELECT NOME, SEXO, BAIRRO, CIDADE
FROM CLIENTE
INNER JOIN ENDERECO
ON IDCLIENTE = ID_CLIENTE;
---------------------------------------------------------------------------------------------------------------------------------------

SELECT NOME, SEXO, BAIRRO, CIDADE 
FROM CLIENTE, ENDERECO 
WHERE IDCLIENTE = ID_CLIENTE   
AND SEXO = 'F'; 

SELECT NOME, SEXO, BAIRRO, CIDADE /* PROJECAO */ 
FROM CLIENTE /* ORIGEM */
INNER JOIN ENDERECO /*JUNCAO */
ON IDCLIENTE = ID_CLIENTE
WHERE SEXO = 'F'; /* SELECAO */

-----------------------------------------------COM 3 TABELAS AGORA ABAIXO--------------------------------------------------------------
/* NOME, SEXO, BAIRRO, CIDADE, TIPO, NUMERO */  

SELECT CLIENTE.NOME, CLIENTE.SEXO, ENDERECO.BAIRRO, ENDERECO.CIDADE, TELEFONE.TIPO, TELEFONE.NUMERO   /*SEM PONTERAMENTO*/
FROM CLIENTE 
INNER JOIN ENDERECO
ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE
INNER JOIN TELEFONE
ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE;


SELECT C.NOME, C.SEXO, E.BAIRRO, E.CIDADE, T.TIPO, T.NUMERO    /*COM PONTERAMENTO,  MUIIIIIITO MELHOR*/
FROM CLIENTE C
INNER JOIN ENDERECO E 
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T 
ON C.IDCLIENTE = T.ID_CLIENTE;




